name: Bug Report
description: File a bug report to help us improve.
labels: [bug]
title: "🐛 Bug Report: "
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide details about the problem.
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Explain what you expected instead.
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        List the steps to reproduce the issue in detail. For example:
          1. Open the application in Google Chrome (v116.0).
          2. Navigate to the "List" page.
          3. Click on the "Add Item" button.
          4. Enter item details (e.g., Name: Milk, Quantity: 2, Expiration: 2025-01-10).
          5. Click the "Save" button.
          6. Observe that the new item does not appear in the list.
      required: true
