# Generated by Django 5.0.7 on 2024-08-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_image',
            fields=[
                ('CategoryImageID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryImage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_image',
            },
        ),
        migrations.CreateModel(
            name='fridge_image',
            fields=[
                ('FridgeImageID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeImage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fridge_image',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Pro', models.BooleanField(default=False)),
                ('Role', models.BooleanField(default=False)),
                ('Block', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=20)),
                ('CategoryImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category_image')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='fridge',
            fields=[
                ('FridgeID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeName', models.CharField(max_length=20)),
                ('FridgeImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge_image')),
            ],
            options={
                'db_table': 'fridge',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('ItemName', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='pro',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('ExpireDate', models.DateTimeField()),
                ('SubscriptionType', models.BooleanField(default=False)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'pro',
            },
        ),
        migrations.CreateModel(
            name='user_fridge',
            fields=[
                ('UserFridgeID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge')),
                ('FridgeImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge_image')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_fridge',
            },
        ),
        migrations.CreateModel(
            name='user_item',
            fields=[
                ('UserItemID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category_image')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('UserFridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user_fridge')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_item',
            },
        ),
        migrations.CreateModel(
            name='user_question',
            fields=[
                ('UserQuestionsID', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=100)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.question')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_question',
            },
        ),
    ]
