# Generated by Django 5.0.7 on 2024-08-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('CategoryImageID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryImage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_image',
            },
        ),
        migrations.CreateModel(
            name='FridgeImage',
            fields=[
                ('FridgeImageID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeImage', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fridge_image',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Pro', models.BooleanField(default=False)),
                ('Role', models.BooleanField(default=False)),
                ('Block', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=20)),
                ('CategoryImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.categoryimage')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('FridgeID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeName', models.CharField(max_length=20)),
                ('FridgeImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fridgeimage')),
            ],
            options={
                'db_table': 'fridge',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpiryDate', models.DateTimeField(blank=True, null=True)),
                ('ItemName', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('ExpireDate', models.DateTimeField()),
                ('SubscriptionType', models.BooleanField(default=False)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'pro',
            },
        ),
        migrations.CreateModel(
            name='UserFridge',
            fields=[
                ('UserFridgeID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge')),
                ('FridgeImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.fridgeimage')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_fridge',
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('UserItemID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.categoryimage')),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('UserFridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.userfridge')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_item',
            },
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('UserQuestionsID', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=100)),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.questions')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'user_questions',
            },
        ),
    ]
