# Generated by Django 5.0.7 on 2024-08-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=20)),
                ('CategoryImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('FridgeID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeName', models.CharField(max_length=20)),
                ('FridgeImage', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('FridgeItemID', models.AutoField(primary_key=True, serialize=False)),
                ('FridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ExpiryDate', models.DateField()),
                ('ItemName', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
                ('Answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=50)),
                ('Pro', models.BooleanField(default=False)),
                ('Role', models.CharField(max_length=20)),
                ('FridgeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.fridge')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('UserItemID', models.AutoField(primary_key=True, serialize=False)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='fridgeitem',
            name='ItemID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
