# Generated by Django 5.0.7 on 2024-08-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='categoryimage',
            table='category_image',
        ),
        migrations.AlterModelTable(
            name='fridge',
            table='fridge',
        ),
        migrations.AlterModelTable(
            name='fridgeimage',
            table='fridge_image',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='pro',
            table='pro',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userfridge',
            table='user_fridge',
        ),
        migrations.AlterModelTable(
            name='useritem',
            table='user_item',
        ),
        migrations.AlterModelTable(
            name='userquestions',
            table='user_questions',
        ),
    ]
