# Generated by Django 5.0.7 on 2024-08-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_table_alter_fridge_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fridgeitem',
            table='fridgeitem',
        ),
    ]
