# Generated by Django 5.0.7 on 2024-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_fridgeitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='FridgeImage',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
