name: Deploy Django Backend to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv handler_venv
        source handler_venv/bin/activate
        pip install --upgrade setuptools==56.0.0  
        pip install -r requirements.txt

    - name: Install distutils
      run: sudo apt-get install python3-distutils

    - name: Deploy to AWS Lambda
      run: |
        source handler_venv/bin/activate
        zappa update dev
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
